### ISSUE TITLE
phantom.mhd

### ISSUE THREAD

**Issue by omrghad** [xcist/main#100]
dear all,
please i have a chest phantom in form .mhd, how can i import it on XCIST for use it in simulation 
regards

**Comment by MingyeWu** [comment]
Hi omrghad, could you explain what is the .mhd phantom?

**Comment by omrghad** [comment]
dear MingyeWu,
it is MetaImage format : header. mhd + raw image .raw (voxelized phantoms), a chest phantom attached below ( i converted CT slice (HU) to Electronic density) and stuck it to form a phantom.
[phantom.zip](https://github.com/user-attachments/files/17088955/phantom.zip)
 else, if there s a patient phantoms compatible with XCIST, please provide me the link 
 regards

**Comment by zhangjy-ge** [comment]
you may define your own voxelized phantom, given that you already have this in .mhd file. Please check an example voxelized phantom here: https://github.com/xcist/example/tree/main/AAPM_datachallenge/simulation_scripts

in which *json file defines material names, voxel size, density, and the phantom.vf file has volume fraction information of the voxelized phantom.

**Comment by PaulFitzGerald** [comment]
Please pay careful attention to the last part of Jiayong's reply - this
sometimes causes confusion. The units of the phantom files (one file for
each material in the phantom) need to be the VOLUME FRACTION of the
material specified in each file associated with the phantom.

Paul

**Comment by omrghad** [comment]
dear all, 
thank you for your reply, really i did not arrive to convert .mhd phantom to .json and .vf files, i tried also with dicom image to phantom (.json and .vf) but i did not get the results.
any help of **how** to convert this phantom to XCIST phantom?
thank you again
regards

**Comment by zhangjy-ge** [comment]
I am not sure how your json file looks like, but it should be like this:
https://github.com/xcist/main/blob/master/gecatsim/phantom/CatSimLogo_1024/CatSimLogo_1024_128mmZ.json

A very important parameter in this file is `volumefractionmap_filename`, which should direct to a binary file, let's say water_512x512x1.vf (the file extension does not matter), in which it specifies the volume fraction of water in a 512x512x1 voxel volume. Each voxel size is defined by `x_size`, `y_size`, `z_size`. Volume fraction of 1 means this voxel has 100% water, of 0.5 means it only has 50% water (other 50% could be air or bone). You can specify multiple materials, as shown in the file. 

When you have a problem, please don't forget to clearly state what you have done/tried, what output you got or what error messages you got, and post your files, so that we can better understand your situation and help you.

**Comment by omrghad** [comment]
Dear all, 
i arrived to solve the issue 
thank you very much
regards
