### ISSUE TITLE
Cannot rebuild with gcc on Mac with M3

### ISSUE THREAD

**Issue by BwKodex** [xcist/main#71]
Trying out the package on a MacBook Pro with an M3 Max processor, I'm trying to follow the instructions in `gecatsim/clib_build/readme.md`.

I've installed `gcc` and `g++` with home-brew and they are now placed under the directory `/opt/homebrew/Cellar/gcc/14.1.0/bin`. After replacing the paths in `MakeVariables_3` and running the rebuild I get the following error

```
#gcc -O0 -g -Wall -static -msse -masm=intel -fPIC -c p_nlog_inline.c
/usr/local/opt/gcc/bin/gcc-14 -O0 -g -Wall -static -msse -fPIC -c p_nlog_inline.c
make: /usr/local/opt/gcc/bin/gcc-14: No such file or directory
make: *** [p_nlog_inline.o] Error 1
```

Is there any more information on how to make this rebuild working? I'm also wondering if there might be a bug somewhere overwriting the path to `gcc` and `g++` specified in `MakeVariables_3` since it specifies a different path to `gcc-14` in the error message compared to the one I specified in `MakeVariables_3`?

**Comment by zhangjy-ge** [comment]
could you try to replace `/usr/local/opt/gcc/bin/gcc-14` in Makefile to `/opt/homebrew/Cellar/gcc/14.1.0/bin`? This is the path to gcc on my computer, so it should be modfied accordingly.

**Comment by BwKodex** [comment]
Thanks for the quick replies!

In my computer homebrew did not add the symlinks. If I remember it correctly that might be a part of a new default for homebrew.

@zhangjy-ge : I tried your tip and got further. Now it tries to use the correct path for gcc, however, I get stuck on it not recognizing the option `-msse`. Do you know if there is something else that needs be done for that option to be available?

```
#gcc -O0 -g -Wall -static -msse -masm=intel -fPIC -c p_nlog_inline.c
/opt/homebrew/Cellar/gcc/14.1.0/bin/gcc-14 -O0 -g -Wall -static -msse -fPIC -c p_nlog_inline.c
gcc-14: error: unrecognized command-line option '-msse'
make: *** [p_nlog_inline.o] Error 1
```

**Comment by jjobin** [comment]
Apparently, the -msse flag is for x86 and x86-64 architectures and not for ARM, which is the case if you have M3 on Mac. You can safely remove that flag in your Makefile. Can you try that and let us know how it goes? Thanks for your patience in working through this.

**Comment by BwKodex** [comment]
Thank you again for your help!

Skipping that flag did the trick! However, I noticed that I also had to recompile the `reconstruction/lib/fdk_equiAngle_macos.so` for everything to work as expected.

What is your policy in this repo? Would you like me to add som clarifications in the respective README-files about what resolved the problem and do a PR or would you prefer to do this yourselves?

**Comment by jjobin** [comment]
We welcome help and contributions of any kind. If it's convenient for you, please create a new branch, add the clarifications in the README files, and open a PR against the 'master' branch. If not convenient, that's ok too. We can update the README files based on the discussion in this thread. Thanks again.

**Comment by jjobin** [comment]
Added some clarification to the readme files in the clib_build and the reconstruction directories. 
Closing this issue.

**Comment by kevin-vmi** [comment]
> Thank you again for your help!
> 
> Skipping that flag did the trick! However, I noticed that I also had to recompile the `reconstruction/lib/fdk_equiAngle_macos.so` for everything to work as expected.
> 

Hello, 

Could you suggest how to recompile fdk_equiAngle_macos.so? I followed the readme in master/gecatsim/reconstruction/lib, but only generated idk_equiAngle.so.

Thanks

**Comment by zhangjy-ge** [comment]
Hi Kevin,

That is because the name in the instruction is `fdk_equiAngle.so`. You may simply rename it to `fdk_equiAngle_macos.so` and copy it to gecatsim\reconstruction\lib.

**Comment by kevin-vmi** [comment]
Thank you, Jiayong! Now I can now run "proj_and_recon" under the AAPM datachallenge. 

My goal is to generate sinograms and their reconstructions from clinical routine CT scans. To run "proj_and_recon" on these scans, my understanding is that I need to first convert DICOMs into appropriate input files, which requires using "DICOM_to_voxelized" to generate. I have two questions:

1. When I try to run the "DICOM_to_voxelized" example using the command "python DICOM_to_voxelized_phantom.py DICOM_to_voxelized_example_neck.cfg", I encounter an error stating: No module named 'catsim'. Could you let me know where I can find the 'catsim' module? I couldn't locate  a module/folder named 'catsim'.

2. Once "DICOM_to_voxelized" runs successfully, it should generate both .raw files and .json files. Since "proj_and_recon" requires only .raw files as input, is it OK to use just .raw files?

Any additional suggestions you have to help achieve my purpose would be greatly appreciated.

**Comment by kevin-vmi** [comment]
Thank you for your prompt response. 

I agree with you that, due to the old scripts, many inconsistencies exist. After modifying "catsim" into "gecatsim", I'm still encountering errors and exceptions. It appears that "DICOM_to_voxelized" may not be an actively maintained or frequently used code.

For my goal of generating sinograms and their reconstructions from clinical routine CT scans (GE scanner), could you kindly suggest how I can obtain the digital phantom from DICOM files to use as input for "proj_and_recon"? As you may have noticed, I am a bit confused about the workflow. 

For example, I noticed in Readme that "proj_and_recon" was used to process the AAPM CT MAR data. Could you point me to an example where AAPM CT scans (DICOM) are being processed? Any guidance you could provide would be very helpful.

**Comment by zhangjy-ge** [comment]
`how I can obtain the digital phantom from DICOM files to use as input for "proj_and_recon"?`
If DICOM_to_voxelized did not work, maybe you can try to read dicom using pydicom, and then extract image and convert the image to a voxelized phantom? In a simplified case, if you have image in HU, you can convert the image to water density using (img+1000)/1000, and use this as the voxelized phantom. You may check MingyeWu's suggestion and https://github.com/xcist/phantoms-voxelized/tree/main/CatSimLogo_1024 for how to define voxelized phantoms.

`For example, I noticed in Readme that "proj_and_recon" was used to process the AAPM CT MAR data. Could you point me to an example where AAPM CT scans (DICOM) are being processed? Any guidance you could provide would be very helpful.`
For the AAPM challenge, the input is not dicom (but .raw in fact) thus no dicom is processes here.
